# Generated by Django 4.2.4 on 2023-08-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_name', models.CharField(max_length=100)),
                ('doc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('UnderProcess', 'Under Process'), ('Processed', 'Processed'), ('UnderReview', 'Under Review'), ('Reviewed', 'Reviewed')], default='New', max_length=15)),
                ('complexity', models.CharField(choices=[('Simple', 'Simple'), ('Complex', 'Complex'), ('VeryComplex', 'Very Complex')], default='Simple', max_length=15)),
                ('type', models.CharField(choices=[('Balance Sheet', 'Blsheet'), ('IncomeStatement', 'Incstmnt'), ('CashFlowStatement', 'Cfsstmnt')], default='Balance Sheet', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_reviwed', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('UnderProcess', 'Under Process'), ('Processed', 'Processed'), ('UnderReview', 'Under Review'), ('Reviewed', 'Reviewed')], max_length=15)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.document', unique=True)),
                ('process_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProcessedByEmp', to='dashboardApi.employee')),
                ('review_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReviewedByEmp', to='dashboardApi.employee')),
            ],
        ),
    ]
