# Generated by Django 4.2.4 on 2023-08-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='total_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('UnderProcess', 'Under Process'), ('Processed', 'Processed'), ('UnderReview', 'Under Review'), ('Reviewed', 'Reviewed')], default='New', editable=False, max_length=15),
        ),
    ]
