# Generated by Django 4.2.4 on 2023-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0004_alter_document_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='total_time',
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
    ]
