# Generated by Django 4.2.4 on 2023-08-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0005_alter_document_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Under Process', 'Under Process'), ('Processed', 'Processed'), ('Under Review', 'Under Review'), ('Reviewed', 'Reviewed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='complexity',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Complex', 'Complex'), ('Very Complex', 'Very Complex')], default='Simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Under Process', 'Under Process'), ('Processed', 'Processed'), ('Under Review', 'Under Review'), ('Reviewed', 'Reviewed')], default='New', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Balance Sheet', 'Blsheet'), ('Income Statement', 'Incstmnt'), ('Cash Flow Statement', 'Cfsstmnt')], default='Balance Sheet', max_length=30),
        ),
    ]
