# Generated by Django 4.2.4 on 2023-09-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0006_alter_assignment_status_alter_document_complexity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documentTrail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='reCheck',
            field=models.BooleanField(default=False),
        ),
    ]
