# Generated by Django 4.2.4 on 2023-09-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0007_document_documenttrail_document_recheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='reCheck',
        ),
        migrations.AddField(
            model_name='document',
            name='NoOfRechecks',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
